### ISSUE TITLE
Diff editor doesn't use Joplin color Theme.

### ISSUE THREAD

**Issue by JackGruber** [joplin/plugin-conflict-resolution#12]
Changes to the Theme of Joplin are not adopted by the editor. 
![grafik](https://user-images.githubusercontent.com/24863925/127817803-64723fa4-ca2b-4f15-808e-05c86e3a6164.png)
Conflict Editor keeps the light colors even if the Theme use dark ones for the editor. 

Possibly the `--joplin-{property}` variables should be used.

**Comment by Ahmad45123** [comment]
Thanks for the report :) I didn't know these --joplin variables existed. It'll be of huge help.
