### ISSUE TITLE
Resolve window not coming up

### ISSUE THREAD

**Issue by ksully-execute** [joplin/plugin-conflict-resolution#18]
Just installed the plugin, restarted the app, right clicked the note in the conflicts folder, but am not getting any window.
The conflict note does have some text shown Joplin.
Am on windows version 2.12.10 (prod, win32)
Any thoughts?

**Comment by CalebJohn** [comment]
To initiate a conflict resolution, you right click on the note (in the note list) and choose to resolve conflict. Is that not working for you?

**Comment by ksully-execute** [comment]
It is not, nothing happens. I tried restarting the app etc as I wrote but no luck

**Comment by bfcs** [comment]
I assume you clicked an attachment conflict

**Comment by ksully-execute** [comment]
I had, yes. Ended up just resetting the app and re-encrypting everything
