### ISSUE TITLE
Context Menu Entry not showing

### ISSUE THREAD

**Issue by Firnin** [joplin/plugin-conflict-resolution#19]
Hello!
After opening Joplin again after quite some time on my PC I had a new Notebook called "Konflikte (Anhänge)" (in english "Conflicts (Attachments)")
I looked up the link in the note, and it told me to install this plugin to help with conflict resolution.
However, after installing the plugin and restarting, I don't see the new context menu entry when right-clicking a note in the conflicts-notebook.
Is there anything I can do to resolve this issue? Do you need further information to help me out? Please let me know!

**Comment by JackGruber** [comment]
Hm sure that this is the Joplin conflicts folder?
The folder should only be named `Conflicts` no Attachments/Anhänge in the name.
![grafik](https://github.com/joplin/plugin-conflict-resolution/assets/24863925/cfe15c5b-6f12-4bfd-8438-1c879384581a)

**Comment by CalebJohn** [comment]
In some cases there can be a conflict within attachments, hence the extra part of the folder name.
I don't believe this plugin has the ability to fix attachment contlicts unfortunately.

**Comment by JackGruber** [comment]
Ok, I have never had that before and did not know that they are handled like this.

No the plugin can only handle note conflicts.

**Comment by Firnin** [comment]
Thank you very much for your replies! Yes, those are conflicts with attachments. Sad to see that this plugin can't solve those, but I will find a way :D
