### ISSUE TITLE
Investigate escaping note contents.

### ISSUE THREAD

**Issue by Ahmad45123** [joplin/plugin-conflict-resolution#2]
Currently, due to the way that I use to pass note contents into the webview, if the note contains a doublequote character, the contents of the note are cut off at that position and the rest of the contents are appended as html. 

In the future, I may look into using an actual escaping library to handle all characters. Also we need to check if we need to "unescape" the notes in the webview side.

**Comment by xUser5000** [comment]
I faced a similar issue while working on my plugin, you can find some details [here](https://github.com/joplin/plugin-bibtex/pull/4#discussion_r653828705). I was able to solve it easily by using `html-entities` package, so you might want to check it out. It's a lightweight escaping library that you can customize according to you your needs.
Good luck :)
